/**
 * The passkey verifier, against payloads a real browser produced.
 *
 * The fixtures in `test/fixtures/webauthn/` were generated by driving
 * Chromium's virtual authenticator over CDP — see
 * `test/tools/make-webauthn-fixtures.mjs`. Nothing here is hand-constructed,
 * which is the point: a verifier tested only against bytes its own author
 * invented tests the author's understanding, not the format.
 */

import { assert, assertEquals, assertRejects, assertThrows } from "@std/assert";
import { fromBase64Url } from "@platform/hash.ts";
import { CborError, decodeCbor, decodeCborItem } from "@auth/webauthn/cbor.ts";
import { CoseError, derToRawEcdsaSignature, importCoseKey } from "@auth/webauthn/cose.ts";
import {
  type ExpectedOrigin,
  parseAuthenticatorData,
  verifyAuthentication,
  verifyRegistration,
  WebAuthnError,
} from "@auth/webauthn/ceremony.ts";

interface Fixture {
  readonly note: string;
  readonly algorithm: number;
  readonly origin: string;
  readonly rpId: string;
  readonly registrationChallenge: string;
  readonly authenticationChallenge: string;
  readonly userHandle: string;
  readonly registration: {
    readonly id: string;
    readonly clientDataJSON: string;
    readonly attestationObject: string;
    readonly transports: string[];
  };
  readonly authentication: {
    readonly id: string;
    readonly clientDataJSON: string;
    readonly authenticatorData: string;
    readonly signature: string;
    readonly userHandle: string | null;
  };
}

function load(name: string): Fixture {
  return JSON.parse(Deno.readTextFileSync(`test/fixtures/webauthn/${name}.json`)) as Fixture;
}

function expectedFor(fixture: Fixture): ExpectedOrigin {
  return { rpId: fixture.rpId, origin: fixture.origin };
}

const es256 = load("es256");
const rs256 = load("rs256");
const noUv = load("no-user-verification");

/* ------------------------------------------------ CBOR -------------------- */

Deno.test("cbor: decodes the shapes WebAuthn uses", () => {
  // {"fmt": "none"} — a text-keyed map with a text value.
  assertEquals(
    decodeCbor(new Uint8Array([0xa1, 0x63, 0x66, 0x6d, 0x74, 0x64, 0x6e, 0x6f, 0x6e, 0x65])),
    new Map([["fmt", "none"]]),
  );
  // {1: 2, 3: -7} — the integer-keyed COSE shape, including a negative.
  assertEquals(
    decodeCbor(new Uint8Array([0xa2, 0x01, 0x02, 0x03, 0x26])),
    new Map<number, number>([[1, 2], [3, -7]]),
  );
  // Byte strings survive as bytes, not as text.
  const bytes = decodeCbor(new Uint8Array([0x43, 0x01, 0x02, 0x03]));
  assert(bytes instanceof Uint8Array);
  assertEquals([...bytes], [1, 2, 3]);
});

Deno.test("cbor: refuses everything outside the canonical subset", () => {
  // Indefinite-length map (0xbf): legal CBOR, illegal CTAP2.
  assertThrows(() => decodeCbor(new Uint8Array([0xbf, 0xff])), CborError, "Indefinite");
  // A tag (major type 6) — nothing in WebAuthn uses one.
  assertThrows(() => decodeCbor(new Uint8Array([0xc0, 0x01])), CborError);
  // Truncated byte string.
  assertThrows(() => decodeCbor(new Uint8Array([0x43, 0x01])), CborError, "Truncated");
  // Trailing bytes after a complete item: two readings of the same payload.
  assertThrows(() => decodeCbor(new Uint8Array([0x01, 0x02])), CborError, "trailing");
  // A repeated key would let one encoding answer the same question twice.
  assertThrows(
    () => decodeCbor(new Uint8Array([0xa2, 0x01, 0x02, 0x01, 0x03])),
    CborError,
    "Duplicate",
  );
});

Deno.test("cbor: reports where an item ended, which is how the COSE key is found", () => {
  // The COSE key inside authenticator data is followed by nothing or by
  // extensions; only the decoder knows where it stops.
  const payload = new Uint8Array([0xa1, 0x01, 0x02, 0xff, 0xff]);
  assertEquals(decodeCborItem(payload, 0).next, 3);
});

/* ------------------------------------------------ DER signatures ---------- */

Deno.test("ecdsa: DER is unpacked to the raw pair WebCrypto wants", () => {
  // r and s both 32 bytes, no sign padding.
  const der = new Uint8Array([
    0x30,
    0x44,
    0x02,
    0x20,
    ...new Array(32).fill(0x11),
    0x02,
    0x20,
    ...new Array(32).fill(0x22),
  ]);
  const raw = derToRawEcdsaSignature(der);
  assertEquals(raw.length, 64);
  assertEquals(raw[0], 0x11);
  assertEquals(raw[32], 0x22);
});

Deno.test("ecdsa: the sign byte comes off and short integers are left-padded", () => {
  // r is 33 bytes with a leading zero (top bit set); s is 31 bytes.
  const r = [0x00, 0x80, ...new Array(31).fill(0x11)];
  const s = new Array(31).fill(0x22);
  const der = new Uint8Array([
    0x30,
    4 + r.length + s.length,
    0x02,
    r.length,
    ...r,
    0x02,
    s.length,
    ...s,
  ]);
  const raw = derToRawEcdsaSignature(der);
  assertEquals(raw.length, 64);
  assertEquals(raw[0], 0x80, "the leading zero must be dropped, not kept");
  assertEquals(raw[32], 0x00, "a short s must be left-padded, not left-aligned");
  assertEquals(raw[33], 0x22);
});

Deno.test("ecdsa: malformed DER is refused rather than guessed at", () => {
  assertThrows(() => derToRawEcdsaSignature(new Uint8Array([0x31, 0x06])), CoseError);
  assertThrows(() => derToRawEcdsaSignature(new Uint8Array(4)), CoseError);
});

/* ------------------------------------------------ registration ------------ */

for (const fixture of [es256, rs256]) {
  const name = fixture.algorithm === -7 ? "ES256" : "RS256";

  Deno.test(`registration verifies a real ${name} credential`, async () => {
    const verified = await verifyRegistration(fixture.registration, expectedFor(fixture));
    assertEquals(verified.credentialId, fixture.registration.id);
    assertEquals(verified.challenge, fixture.registrationChallenge);
    assertEquals(verified.attestationFormat, "none");
    assert(verified.publicKey.length > 0);
    // The stored key must be importable, since that is what every later login
    // depends on.
    const key = await importCoseKey(fromBase64Url(verified.publicKey));
    assertEquals(key.algorithm, fixture.algorithm);
  });

  Deno.test(`authentication verifies a real ${name} assertion`, async () => {
    const registered = await verifyRegistration(fixture.registration, expectedFor(fixture));
    const verified = await verifyAuthentication(
      { ...fixture.authentication, credentialId: fixture.authentication.id },
      {
        credentialId: registered.credentialId,
        publicKey: registered.publicKey,
        signCount: registered.signCount,
      },
      expectedFor(fixture),
    );
    assertEquals(verified.challenge, fixture.authenticationChallenge);
    assertEquals(verified.credentialId, fixture.registration.id);
  });
}

Deno.test("the credential is discoverable, so it carries the user handle back", () => {
  assertEquals(es256.authentication.userHandle, es256.userHandle);
});

/* ------------------------------------------------ the checks that matter -- */

Deno.test("a ceremony performed at another origin is refused", async () => {
  await assertRejects(
    () =>
      verifyRegistration(es256.registration, {
        rpId: es256.rpId,
        origin: "https://phishing.example",
      }),
    WebAuthnError,
    "not this origin",
  );
});

Deno.test("a credential scoped to another site is refused", async () => {
  // The origin still matches, so only the rpId hash inside authenticator data
  // can catch this — which is exactly the case the hash check exists for.
  await assertRejects(
    () => verifyRegistration(es256.registration, { rpId: "evil.example", origin: es256.origin }),
    WebAuthnError,
    "different site",
  );
});

Deno.test("a registration response cannot be replayed as a sign-in", async () => {
  const registered = await verifyRegistration(es256.registration, expectedFor(es256));
  await assertRejects(
    () =>
      verifyAuthentication({
        credentialId: registered.credentialId,
        clientDataJSON: es256.registration.clientDataJSON,
        authenticatorData: es256.authentication.authenticatorData,
        signature: es256.authentication.signature,
      }, {
        credentialId: registered.credentialId,
        publicKey: registered.publicKey,
        signCount: 0,
      }, expectedFor(es256)),
    WebAuthnError,
    "webauthn.get",
  );
});

Deno.test("an authenticator that only proved presence is refused", async () => {
  await assertRejects(
    () => verifyRegistration(noUv.registration, expectedFor(noUv)),
    WebAuthnError,
    "did not verify who you are",
  );

  const authData = parseAuthenticatorData(fromBase64Url(noUv.authentication.authenticatorData));
  assertEquals(authData.userPresent, true, "the fixture should still show presence");
  assertEquals(authData.userVerified, false, "…and that is precisely what is not enough");
});

Deno.test("a tampered signature does not verify", async () => {
  const registered = await verifyRegistration(es256.registration, expectedFor(es256));
  const signature = fromBase64Url(es256.authentication.signature);
  // Flip a bit inside the DER-encoded s value.
  signature[signature.length - 1] = (signature.at(-1) ?? 0) ^ 0x01;
  let flipped = "";
  for (const byte of signature) flipped += String.fromCharCode(byte);
  const encoded = btoa(flipped).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "");

  await assertRejects(
    () =>
      verifyAuthentication(
        { ...es256.authentication, credentialId: registered.credentialId, signature: encoded },
        {
          credentialId: registered.credentialId,
          publicKey: registered.publicKey,
          signCount: registered.signCount,
        },
        expectedFor(es256),
      ),
    WebAuthnError,
    "does not verify",
  );
});

Deno.test("one credential's signature does not verify under another's key", async () => {
  const mine = await verifyRegistration(es256.registration, expectedFor(es256));
  const theirs = await verifyRegistration(rs256.registration, expectedFor(rs256));

  await assertRejects(
    () =>
      verifyAuthentication(
        { ...es256.authentication, credentialId: mine.credentialId },
        { credentialId: mine.credentialId, publicKey: theirs.publicKey, signCount: 0 },
        expectedFor(es256),
      ),
    Error, // an RSA key over an ECDSA signature fails at verification either way
  );
});

Deno.test("a counter that goes backwards means a possible clone", async () => {
  const registered = await verifyRegistration(es256.registration, expectedFor(es256));
  const authData = parseAuthenticatorData(fromBase64Url(es256.authentication.authenticatorData));

  await assertRejects(
    () =>
      verifyAuthentication(
        { ...es256.authentication, credentialId: registered.credentialId },
        {
          credentialId: registered.credentialId,
          publicKey: registered.publicKey,
          // Pretend we have already seen a later use than this response claims.
          signCount: authData.signCount + 5,
        },
        expectedFor(es256),
      ),
    WebAuthnError,
    "counter went backwards",
  );
});

Deno.test("an authenticator that never counts is not treated as a clone", async () => {
  // Both sides zero: the check does not apply, per the spec's own guidance.
  const registered = await verifyRegistration(es256.registration, expectedFor(es256));
  const authData = parseAuthenticatorData(fromBase64Url(es256.authentication.authenticatorData));
  if (authData.signCount !== 0) return; // Chromium's virtual authenticator does count.

  const verified = await verifyAuthentication(
    { ...es256.authentication, credentialId: registered.credentialId },
    { credentialId: registered.credentialId, publicKey: registered.publicKey, signCount: 0 },
    expectedFor(es256),
  );
  assertEquals(verified.signCount, 0);
});

Deno.test("a response for a different credential id is refused before any crypto", async () => {
  const registered = await verifyRegistration(es256.registration, expectedFor(es256));
  await assertRejects(
    () =>
      verifyAuthentication(
        { ...es256.authentication, credentialId: "some-other-credential" },
        {
          credentialId: registered.credentialId,
          publicKey: registered.publicKey,
          signCount: 0,
        },
        expectedFor(es256),
      ),
    WebAuthnError,
    "different credential",
  );
});

Deno.test("garbage in the fields is a rejection, not a crash", async () => {
  for (const field of ["clientDataJSON", "attestationObject"] as const) {
    await assertRejects(
      () =>
        verifyRegistration(
          { ...es256.registration, [field]: "!!!not base64!!!" },
          expectedFor(es256),
        ),
      WebAuthnError,
    );
    await assertRejects(
      () => verifyRegistration({ ...es256.registration, [field]: "" }, expectedFor(es256)),
      WebAuthnError,
    );
  }
});

Deno.test("an unsupported algorithm is named rather than silently trusted", async () => {
  // A COSE key claiming EdDSA (-8), which this application does not verify.
  const eddsa = new Uint8Array([
    0xa4,
    0x01,
    0x01, // kty: OKP
    0x03,
    0x27, // alg: -8
    0x20,
    0x06, // crv: Ed25519
    0x21,
    0x40, // x: empty
  ]);
  await assertRejects(() => importCoseKey(eddsa), CoseError, "Unsupported COSE algorithm");
});

Deno.test("authenticator data shorter than the header is refused", () => {
  assertThrows(() => parseAuthenticatorData(new Uint8Array(36)), WebAuthnError, "too short");
});
